version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: charity_postgres
    environment:
      POSTGRES_DB: lewisham_hub
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d lewisham_hub"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - charity_network

  redis:
    image: redis:7-alpine
    container_name: charity_redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - charity_network

  # Redis Commander for Redis management (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: charity_redis_commander
    environment:
      - REDIS_HOSTS=local:charity_redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - charity_network
    profiles:
      - tools

  # pgAdmin for PostgreSQL management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: charity_pgadmin
    environment:
      # Set these via environment variables or an .env file for local development.
      # Do NOT commit real credentials into source control.
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@charity.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - charity_network
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  charity_network:
    driver: bridge