services:
  - type: web
    name: charity-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: charity-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: charity-redis
          type: redis
      - key: JWT_SECRET
        generateValue: true
  - type: redis
    name: charity-redis
    plan: free
    region: oregon
    ipAllowList: []

databases:
  - name: charity-db
    plan: free
    region: oregon
